name: city_inquiry
channels:
- defaults
dependencies:
- certifi=2016.2.28=py36_0
- openssl=1.0.2l=0
- pip=9.0.1=py36_1
- python=3.6.2=0
- readline=6.2=2
- setuptools=36.4.0=py36_1
- sqlite=3.13.0=0
- tk=8.5.18=0
- wheel=0.29.0=py36_0
- xz=5.2.3=0
- zlib=1.2.11=0
- pip:
  - babel==2.5.1
  - blinker==1.4
  - chardet==3.0.4
  - click==6.7
  - coverage==4.4.1
  - decorator==4.1.2
  - defusedxml==0.5.0
  - flake8==3.4.1
  - flask==0.12.2
  - flask-babel==0.11.2
  - flask-login==0.4.0
  - flask-mail==0.9.1
  - flask-openid==1.2.5
  - flask-sqlalchemy==2.3.0
  - flask-whooshalchemy==0.56
  - flask-wtf==0.14.2
  - flipflop==1.0
  - geocoder==1.32.1
  - greenlet==0.4.12
  - guess-language==0.2
  - idna==2.6
  - itsdangerous==0.24
  - jinja2==2.9.6
  - markupsafe==1.0
  - mccabe==0.6.1
  - msgpack-python==0.4.8
  - neovim==0.1.13
  - oauthlib==2.0.4
  - pbr==3.1.1
  - pycodestyle==2.3.1
  - pyflakes==1.5.0
  - pyowm==2.7.1
  - python3-openid==3.1.0
  - pytz==2017.2
  - ratelim==0.1.6
  - requests==2.18.4
  - requests-oauthlib==0.8.0
  - six==1.11.0
  - sqlalchemy==1.1.14
  - sqlalchemy-migrate==0.11.0
  - sqlparse==0.2.4
  - tempita==0.5.2
  - tweepy==3.5.0
  - urllib3==1.22
  - werkzeug==0.12.2
  - whoosh==2.7.4
  - wtforms==2.1
